"""add html_snapshot_path to papers table

Revision ID: 03b4cd44700f
Revises: 2be4589a53bb
Create Date: 2025-10-07 17:04:59.678450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03b4cd44700f"
down_revision: Union[str, Sequence[str], None] = "2be4589a53bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers", sa.Column("html_snapshot_path", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "html_snapshot_path")
    # ### end Alembic commands ###
