"""add last_modified to collections

Revision ID: 2be4589a53bb
Revises: b0c3d711e447
Create Date: 2025-08-05 02:39:44.298182

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2be4589a53bb"
down_revision: Union[str, Sequence[str], None] = "b0c3d711e447"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to add a non-nullable column
    # First add the column as nullable
    op.add_column(
        "collections", sa.Column("last_modified", sa.DateTime(), nullable=True)
    )

    # Set default value for existing collections to match their created_at
    op.execute(
        "UPDATE collections SET last_modified = created_at WHERE last_modified IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "last_modified")
    # ### end Alembic commands ###
